#!/usr/bin/env bash
set -euo pipefail

prefix="${XDG_DATA_HOME:-$HOME/.local/share}/ayame-shell"
assume_yes=false
install_dependencies=true
for argument in "$@"; do
    case "$argument" in
        --yes) assume_yes=true ;;
        --no-install-deps) install_dependencies=false ;;
        --prefix=*) prefix="${argument#*=}" ;;
        *) echo "Unknown option: $argument" >&2; exit 2 ;;
    esac
done

source_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
bin_dir="${XDG_BIN_HOME:-$HOME/.local/bin}"
hypr_dir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
hypr_main="$hypr_dir/hyprland.conf"
hypr_fragment="$hypr_dir/ayame-shell.conf"
timestamp="$(date +%Y%m%d-%H%M%S)"

required=(qs hyprctl hyprlock grim slurp wl-copy kitty)
declare -A command_packages=(
    [qs]=quickshell
    [hyprctl]=hyprland
    [hyprlock]=hyprlock
    [grim]=grim
    [slurp]=slurp
    [wl-copy]=wl-clipboard
    [kitty]=kitty
)
missing=()
for command_name in "${required[@]}"; do
    command -v "$command_name" >/dev/null 2>&1 || missing+=("$command_name")
done
if ((${#missing[@]})); then
    printf 'Missing required commands: %s\n' "${missing[*]}"
    missing_packages=()
    for command_name in "${missing[@]}"; do
        package_name="${command_packages[$command_name]}"
        [[ " ${missing_packages[*]} " == *" $package_name "* ]] \
            || missing_packages+=("$package_name")
    done
    printf 'Packages needed: %s\n' "${missing_packages[*]}"

    if [[ "$install_dependencies" != true ]]; then
        echo "Dependency installation was disabled with --no-install-deps." >&2
        exit 1
    fi
    if ! command -v pacman >/dev/null 2>&1; then
        echo "Automatic dependencies currently require Arch Linux or EndeavourOS with pacman." >&2
        exit 1
    fi
    if [[ "$assume_yes" == true ]]; then
        dependency_answer=y
    else
        read -r -p "Install the missing packages with pacman now? [y/N] " dependency_answer
    fi
    if [[ ! "$dependency_answer" =~ ^[Yy]$ ]]; then
        echo "Install the listed packages, then run this installer again." >&2
        exit 1
    fi
    sudo pacman -S --needed "${missing_packages[@]}"

    still_missing=()
    for command_name in "${required[@]}"; do
        command -v "$command_name" >/dev/null 2>&1 || still_missing+=("$command_name")
    done
    if ((${#still_missing[@]})); then
        printf 'Commands still missing after package installation: %s\n' \
            "${still_missing[*]}" >&2
        exit 1
    fi
fi

echo "Ayame Shell installer"
echo "  Source:      $source_dir"
echo "  Destination: $prefix"
echo "  Launcher:    $bin_dir/ayame-shell"
echo "  Hyprland:    $hypr_fragment"
if [[ "$assume_yes" != true ]]; then
    read -r -p "Continue? [y/N] " answer
    [[ "$answer" =~ ^[Yy]$ ]] || exit 0
fi

mkdir -p "$(dirname -- "$prefix")" "$bin_dir" "$hypr_dir"
if [[ -e "$prefix" ]]; then
    backup="${prefix}.backup-${timestamp}"
    echo "Backing up the previous Ayame installation to $backup"
    mv -- "$prefix" "$backup"
fi

mkdir -p "$prefix"
cp -a "$source_dir/assets" "$source_dir/config" "$source_dir/docs" \
    "$source_dir/scripts" "$source_dir/themes" "$source_dir/README.md" \
    "$source_dir/uninstall.sh" "$prefix/"
chmod +x "$prefix/scripts/ayame-screenshot.sh" "$prefix/uninstall.sh"

cat > "$bin_dir/ayame-shell" <<EOF
#!/usr/bin/env bash
exec qs --path "$prefix/config/quickshell" "\$@"
EOF
chmod +x "$bin_dir/ayame-shell"

monitor="$(hyprctl monitors 2>/dev/null | awk '/^Monitor / {print $2; exit}' || true)"
cat > "$hypr_fragment" <<EOF
# Generated by Ayame Shell. Edit or remove safely.
exec-once = $bin_dir/ayame-shell
bindr = SUPER, SUPER_L, exec, $bin_dir/ayame-shell ipc call launcher toggle
bind = SUPER, RETURN, exec, kitty
bind = SUPER, F, fullscreen, 0
bind = SUPER SHIFT, F, togglefloating
bind = SUPER, Q, killactive
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = , PRINT, exec, $prefix/scripts/ayame-screenshot.sh desktop 0
bind = SHIFT, PRINT, exec, $prefix/scripts/ayame-screenshot.sh area 0
bind = SUPER, PRINT, exec, $prefix/scripts/ayame-screenshot.sh monitor 0 ${monitor:-AUTO}
EOF

if [[ ! -f "$hypr_main" ]]; then
    if [[ "$assume_yes" == true ]]; then
        link_answer=y
    else
        read -r -p "Create a new Hyprland profile and start Ayame on Hyprland login? [y/N] " link_answer
    fi
    if [[ "$link_answer" =~ ^[Yy]$ ]]; then
        cat > "$hypr_main" <<EOF
# Created by Ayame Shell for a new Hyprland profile.

# Ayame Shell
source = $hypr_fragment
EOF
        echo "Created $hypr_main and enabled Ayame for Hyprland logins."
    fi
elif ! grep -Fq "source = $hypr_fragment" "$hypr_main"; then
    if [[ "$assume_yes" == true ]]; then
        link_answer=y
    else
        read -r -p "Enable Ayame in $hypr_main now? [y/N] " link_answer
    fi
    if [[ "$link_answer" =~ ^[Yy]$ ]]; then
        cp -a "$hypr_main" "$hypr_main.ayame-backup-$timestamp"
        printf '\n# Ayame Shell\nsource = %s\n' "$hypr_fragment" >> "$hypr_main"
        echo "Backed up Hyprland configuration before adding the source line."
    fi
fi

echo
echo "Ayame Shell is installed."
echo "Run now:  $bin_dir/ayame-shell"
echo "Uninstall: $prefix/uninstall.sh --prefix=$prefix"
echo "Log out and back in after enabling the Hyprland fragment."
