#!/usr/bin/env bash
set -euo pipefail

target="${XDG_CONFIG_HOME:-$HOME/.config}/kitty/ayame-colors.conf"
[[ -f "$target" ]] || exit 0
if (($# != 10)); then
    echo "Expected 10 palette colors" >&2
    exit 2
fi
for color in "$@"; do
    [[ "$color" =~ ^#[0-9A-Fa-f]{6}$ ]] || { echo "Invalid palette color" >&2; exit 2; }
done

background=$1 foreground=$2 primary=$3 on_primary=$4 surface=$5
surface_high=$6 outline=$7 error=$8 success=$9 warning=${10}
temporary="$(mktemp --tmpdir="$(dirname -- "$target")" .ayame-colors.XXXXXX)"
trap 'rm -f "$temporary"' EXIT
printf '%s\n' \
    '# Generated by Ayame Shell' \
    "background $background" "foreground $foreground" \
    "selection_background $primary" "selection_foreground $on_primary" \
    "cursor $primary" "cursor_text_color $on_primary" "url_color $primary" \
    "active_tab_background $primary" "active_tab_foreground $on_primary" \
    "inactive_tab_background $surface_high" "inactive_tab_foreground $foreground" \
    "color0 $surface" "color1 $error" "color2 $success" "color3 $warning" \
    "color4 $primary" "color5 $primary" "color6 $outline" "color7 $foreground" \
    "color8 $outline" "color9 $error" "color10 $success" "color11 $warning" \
    "color12 $primary" "color13 $primary" "color14 $outline" "color15 $foreground" \
    > "$temporary"
mv -f -- "$temporary" "$target"
trap - EXIT
pkill -USR1 -x kitty 2>/dev/null || true
