#!/usr/bin/env bash
set -euo pipefail

target="${XDG_CONFIG_HOME:-$HOME/.config}/kitty/ayame-colors.conf"
[[ -f "$target" ]] || exit 0
if (($# != 10)); then
    echo "Expected 10 palette colors" >&2
    exit 2
fi
for color in "$@"; do
    [[ "$color" =~ ^#[0-9A-Fa-f]{6}$ ]] || { echo "Invalid palette color" >&2; exit 2; }
done

background=$1 foreground=$2 primary=$3 on_primary=$4 surface=$5
surface_high=$6 outline=$7 error=$8 success=$9 warning=${10}

# ANSI black cannot reuse a pale surface in light mode: many terminal programs
# explicitly request color0 for text, which would then vanish into the
# background. Detect the generated background brightness and choose readable
# neutral slots for the active appearance.
background_hex=${background#\#}
red=$((16#${background_hex:0:2}))
green=$((16#${background_hex:2:2}))
blue=$((16#${background_hex:4:2}))
luminance=$((299 * red + 587 * green + 114 * blue))
if ((luminance > 128000)); then
    appearance_mode=light
    ansi_black=$foreground
    ansi_white=$outline
    ansi_bright_black=$outline
    ansi_bright_white=$foreground
else
    appearance_mode=dark
    ansi_black=$surface
    ansi_white=$foreground
    ansi_bright_black=$outline
    ansi_bright_white=$foreground
fi

temporary="$(mktemp --tmpdir="$(dirname -- "$target")" .ayame-colors.XXXXXX)"
trap 'rm -f "$temporary"' EXIT
printf '%s\n' \
    '# Generated by Ayame Shell' \
    "background $background" "foreground $foreground" \
    "selection_background $primary" "selection_foreground $on_primary" \
    "cursor $primary" "cursor_text_color $on_primary" "url_color $primary" \
    "active_tab_background $primary" "active_tab_foreground $on_primary" \
    "inactive_tab_background $surface_high" "inactive_tab_foreground $foreground" \
    "color0 $ansi_black" "color1 $error" "color2 $success" "color3 $warning" \
    "color4 $primary" "color5 $primary" "color6 $outline" "color7 $ansi_white" \
    "color8 $ansi_bright_black" "color9 $error" "color10 $success" "color11 $warning" \
    "color12 $primary" "color13 $primary" "color14 $outline" "color15 $ansi_bright_white" \
    > "$temporary"
mv -f -- "$temporary" "$target"
trap - EXIT
pkill -USR1 -x kitty 2>/dev/null || true
# A palette reload can leave the current frame using a mixture of the old and
# new colors until Kitty receives another surface event. Prompt that redraw so
# users do not have to unfocus and refocus the terminal manually.
sleep 0.08
pkill -WINCH -x kitty 2>/dev/null || true

# Kitty palette updates are the most reliable appearance signal during a live
# Quickshell session. Use the same detected mode for all other application
# toolkits so KDE/Qt/GTK cannot drift away from Ayame in Hyprland or a VM.
appearance_script="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/ayame-appearance-mode.sh"
if [[ -x "$appearance_script" ]]; then
    "$appearance_script" "$appearance_mode" >/dev/null 2>&1 || true
fi
